# Generated by Django 4.2.4 on 2023-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliancesSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FashionSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportsAndLeisureSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WatchesSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('appliances_sub_category', models.ManyToManyField(to='category.appliancessubcategory')),
                ('electronics_sub_category', models.ManyToManyField(to='category.electronicssubcategory')),
                ('fashion_sub_category', models.ManyToManyField(to='category.fashionsubcategory')),
                ('sports_and_leisure_sub_category', models.ManyToManyField(to='category.sportsandleisuresubcategory')),
                ('watches_sub_category', models.ManyToManyField(to='category.watchessubcategory')),
            ],
        ),
    ]
