# Generated by Django 4.2.4 on 2023-08-13 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliancesSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FashionSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportsAndLeisureSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WatchesSubCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='product_image_height', null=True, upload_to='products/', width_field='product_image_width'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_width',
            field=models.PositiveIntegerField(default=553),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='appliances_sub_category',
            field=models.ManyToManyField(null=True, to='products.appliancessubcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='electronics_sub_category',
            field=models.ManyToManyField(null=True, to='products.electronicssubcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='fashion_sub_category',
            field=models.ManyToManyField(null=True, to='products.fashionsubcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='sports_and_leisure_sub_category',
            field=models.ManyToManyField(null=True, to='products.sportsandleisuresubcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='watches_sub_category',
            field=models.ManyToManyField(null=True, to='products.watchessubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='appliances_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.appliancessubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='electronics_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.electronicssubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='fashion_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.fashionsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='sports_and_leisure_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.sportsandleisuresubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='watches_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.watchessubcategory'),
        ),
    ]
