# Generated by Django 4.2.4 on 2023-08-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0003_alter_category_appliances_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='appliances_sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='electronics_sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fashion_sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sports_and_leisure_sub_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='watches_sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='appliances_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.appliancessubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='electronics_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.electronicssubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fashion_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.fashionsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sports_and_leisure_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.sportsandleisuresubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='watches_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.watchessubcategory'),
        ),
        migrations.DeleteModel(
            name='AppliancesSubCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ElectronicsSubCategory',
        ),
        migrations.DeleteModel(
            name='FashionSubCategory',
        ),
        migrations.DeleteModel(
            name='SportsAndLeisureSubCategory',
        ),
        migrations.DeleteModel(
            name='WatchesSubCategory',
        ),
    ]
