# Generated by Django 4.2.4 on 2023-08-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_features_product_price_product_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
