# Generated by Django 4.2.4 on 2023-08-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='title',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='id',
        ),
    ]
