# Generated by Django 4.2.4 on 2023-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_width',
            field=models.PositiveIntegerField(default=553),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='product_image_height', null=True, upload_to='', width_field='product_image_width'),
        ),
    ]
