# Generated by Django 4.2.4 on 2023-08-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_appliances_sub_category_and_more'),
        ('products', '0007_alter_product_appliances_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='appliances_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.appliancessubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='electronics_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.electronicssubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fashion_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.fashionsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sports_and_leisure_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.sportsandleisuresubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='watches_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.watchessubcategory'),
        ),
    ]
