# Generated by Django 4.2.4 on 2023-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='product_image_height', null=True, upload_to='products/<function product_image_upload at 0x000002419E3130A0>/', width_field='product_image_width'),
        ),
    ]
