# Generated by Django 4.2.4 on 2023-08-06 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_product_image_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4c10105-1474-4dfc-a66e-043bfa40ba96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='product_image_height', null=True, upload_to='products/e4c1010514744dfca66e043bfa40ba96/', width_field='product_image_width'),
        ),
    ]
