# Generated by Django 4.2.4 on 2023-08-06 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_id_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='product_image_height', null=True, upload_to='products/826f8e5e3a644d4d9933f137299034e9/', width_field='product_image_width'),
        ),
    ]
